spring:
  profiles: 
    active:
    - develop
  thymeleaf:
    mode: HTML
    #prefix resource配下を指定する
    prefix: classpath:/templates/
    #suffix ファイル形式(拡張子)
    suffix: .html
    #encoding テンプレートを読み込む際のエンコーディング
    encoding: UTF-8
    #cache デフォルトはオフ
    cache: false
    #content-type
    servlet:
      content-type: text/html; charset=utf-8

  #データベース情報
  datasource:    url: jdbc:mysql://localhost:3306/royale_mahi?serverTimezone=JST
    username: royale
    password: royale
    driverClassName: com.mysql.jdbc.Driver

#サーバー情報
server:
  port: 8081
  servlet:
    context-path: /royale-mahi